version: "3.9"
services:
  localstack:
    image: localstack/localstack:3
    container_name: exersio-localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEFAULT_REGION=eu-west-3
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  localstack_data:
