apiVersion: v1
kind: Service
metadata:
  name: exersio-backend
  namespace: exersio
spec:
  selector:
    app: exersio-backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exersio-backend
  namespace: exersio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exersio-backend
  template:
    metadata:
      labels:
        app: exersio-backend
    spec:
      initContainers:
      - name: prisma-migrate
        image: exersio/backend:latest
        command: ["npx", "prisma", "migrate", "deploy"]
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: exersio-secrets
              key: DATABASE_URL
      containers:
      - name: exersio-backend
        image: exersio/backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: exersio-config
              key: PORT
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: exersio-config
              key: NODE_ENV
        - name: CORS_ORIGIN
          valueFrom:
            configMapKeyRef:
              name: exersio-config
              key: CORS_ORIGIN
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: exersio-config
              key: AWS_REGION
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: exersio-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: exersio-secrets
              key: JWT_SECRET
        - name: EMAIL_HOST
          valueFrom:
            secretKeyRef:
              name: exersio-secrets
              key: EMAIL_HOST
        - name: EMAIL_PORT
          valueFrom:
            secretKeyRef:
              name: exersio-secrets
              key: EMAIL_PORT
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: exersio-secrets
              key: EMAIL_USER
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: exersio-secrets
              key: EMAIL_PASSWORD
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: exersio-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: exersio-secrets
              key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
        - name: logs-volume
          mountPath: /app/logs
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: logs-volume
        emptyDir: {}